hmily:
   admin :
      retryMax : 10
      repository : mysql
      hmilyDbConfig :
            driverClassName:  com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/hmily?useUnicode=true&amp;characterEncoding=utf8
            username: root
            password: